name: Deploy Images to GHCR


on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: windows-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              docker build . --tag ghcr.io/lawrence-d-lee/housing_app:latest
              docker push ghcr.io/lawrence-d-lee/housing_app:latest
