name: Deploy Images to GHCR


on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main
         
          - name: Set up Python 3.9
            uses: actions/setup-python@v3
            with:
              python-version: "3.9"

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

          - name: Test with pytest
            run: |
              pytest

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              docker build . --tag ghcr.io/lawrence-d-lee/housing_app:latest
              docker push ghcr.io/lawrence-d-lee/housing_app:latest
